### PR TITLE
Fixed deprecation warning for Node v6

### PR DESCRIPTION
**Pull request by njam3**

### CODE REVIEW

**Comment by njam3** [comment]
@saintedlama Please take a look at the PR and let me know if there is anything i should change.

**Comment by saintedlama** [comment]
@njam3 this change breaks the build for older node.js 0.10 versions.

**Comment by saintedlama** [comment]
@will use a code snippet from passport-local-mongoose to call the function with appropriate digest options set depending on node.js versions

**Comment by will** [comment]
Mongoose sounds like a mongo thing, but I mostly use Postgres. And redis I
suppose.

**Comment by njam3** [comment]
@saintedlama I updated the PR

**Comment by saintedlama** [comment]
Implemented and pushed - @will no fear, no mongogb dependency leaked in :dancer:

**Pull request closed without merging**
